name: jobtest

on:
  push:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.7.1
    - run: julia -e 'println("Hello, World!")'
